# Generated by Django 2.1 on 2018-08-17 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='중분류명')),
            ],
            options={
                'verbose_name': '중분류',
                'verbose_name_plural': '중분류 목록',
            },
        ),
        migrations.CreateModel(
            name='ProductCategorySmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='소분류명')),
                ('middle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.ProductCategoryMiddle', verbose_name='중분류')),
            ],
            options={
                'verbose_name': '소분류',
                'verbose_name_plural': '소분류 목록',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '최상위 카테고리',
                'verbose_name_plural': '최상위 카테고리 목록',
            },
        ),
        migrations.AddField(
            model_name='productcategorymiddle',
            name='top_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.ProductCategoryTop', verbose_name='최상위 카테고리'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='productcategorysmall',
            order_with_respect_to='middle_category',
        ),
        migrations.AlterOrderWithRespectTo(
            name='productcategorymiddle',
            order_with_respect_to='top_category',
        ),
    ]
