# Generated by Django 2.1 on 2018-08-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='옵션명')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_set', to='products.Product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 옵션',
                'verbose_name_plural': '상품 옵션 목록',
            },
        ),
        migrations.CreateModel(
            name='ProductOptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='가격')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='적용일시')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_set', to='products.ProductOption', verbose_name='상품옵션')),
            ],
            options={
                'verbose_name': '상품옵션 가격',
                'verbose_name_plural': '상품옵션 가격 목록',
                'ordering': ('-start_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductOptionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(default=1, verbose_name='단위수량')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='적용일시')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_set', to='products.ProductOption', verbose_name='상품옵션')),
            ],
            options={
                'verbose_name': '상품옵션 단위수량',
                'verbose_name_plural': '상품옵션 단위수량 목록',
                'ordering': ('-start_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': '상품 카테고리', 'verbose_name_plural': '상품 카테고리 목록'},
        ),
    ]
