# Generated by Django 2.1 on 2018-08-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180823_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptionprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='가격'),
        ),
    ]
