# Generated by Django 2.1.1 on 2018-10-03 15:13

from django.db import migrations, models
import django.db.models.deletion
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180824_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=utils.helpers.RandomFileName('product'), verbose_name='상품 이미지')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지 목록',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to=utils.helpers.RandomFileName('product'), verbose_name='커버 이미지'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='products.Product', verbose_name='상품'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='productimage',
            order_with_respect_to='product',
        ),
    ]
